
# 容器方面配置
server:
  port: 8080


# spring管理配置
spring:
  #数据库池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music_player
    username: root
    password: 123456

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      location: D:/Music
      resolve-lazily: true


#工具类配置
bcrypt:
  strength: 10
jwt:
  default-secret: QxAuutYSQ3a7zIoBeBMl3WY+qfFefVic6PcPYXNJC1zAHVWKf18rO+4aasDLsyve8OrA3u/xSV4gsZGw6d4gvA==


#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#拦截器
interceptor:
  login-exclude-path:
    - /user/login
    - /admin/register

